lib/standup_web/router.ex
defmodule StandupWeb.Router do
  use StandupWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Pjax.Plugs.Pjax)
  end

  # pipeline :browser_auth do
  #   plug Guardian.Plug.VerifySession
  #   plug Guardian.Plug.EnsureAuthenticated, handler: Standup.AuthErrorHandler
  #   plug Guardian.Plug.LoadResource, allow_blank: true
  #   plug Standup.CurrentUser
  # end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end
  pipeline :browser_session do
    plug(Standup.Guardian.AuthPipeline.Browser)
    plug(Standup.Auth.CurrentUser)
  end

  pipeline :login_required do
    plug(Standup.Guardian.AuthPipeline.Authenticate)
  end

  # pipeline :authorize_admin do
  #   plug Standup.Guardian.AuthPipeline.Authenticate
  #   plug Standup.Auth.Authorize, :admin
  # end

  pipeline :api do
    plug(:accepts, ["json"])
    plug(Standup.Guardian.AuthPipeline.JSON)
  end

  scope "/auth", StandupWeb do
    pipe_through([:browser, :browser_session])

    get("/:provider", AuthController, :new)
    get("/:provider/callback", AuthController, :callback)
    post("/identity/callback", AuthController, :identity_callback)
    delete("/delete", AuthController, :delete)
  end

  scope "/", StandupWeb do
    pipe_through([:browser, :browser_session])

    resources("/users", UserController, only: [:new, :create])
  end

  scope "/", StandupWeb do
    # Use the default browser stack
    pipe_through([:browser, :browser_session, :login_required])

    get("/", PageController, :index)
    resources("/users", UserController, except: [:new, :create])
    resources("/roles", RoleController)

    resources "/organizations", OrganizationController do
      resources("/domains", DomainController)
      resources("/work_status_types", WorkStatusTypeController)
      resources("/spreadsheets", SpreadsheetController)
      resources("/to_dos", ToDoController)
    end

    resources "/to_dos", ToDoController, only: [], as: :to_do do
      resources("/to_do_users", ToDoUserController, as: :users)
    end

    resources "/teams", TeamController do
      get("/add_users", TeamController, :add_users, as: :add_users)
      get("/remove_users", TeamController, :remove_users, as: :remove_users)
      get("/set_as_moderator", TeamController, :set_as_moderator, as: :set_as_moderator)
      get("/set_as_member", TeamController, :set_as_member, as: :set_as_member)
    end

    post("/photos/upload", PhotoController, :upload)

    resources "/work_statuses", WorkStatusController do
      resources("/key_result_areas", KeyResultAreaController)
      resources("/comments", CommentController)
    end

    get("/team_work_statuses", WorkStatusController, :team_work_statuses, as: :team_work_statuses)
    resources("/tasks", TaskController)

    get(
      "/export_to_do_to_tasks",
      TaskController,
      :export_to_do_to_tasks,
      as: :export_to_do_to_tasks
    )

    get("/team_to_dos", ToDoController, :team_to_dos, as: :team_to_dos)
  end

  # Other scopes may use custom stacks.
  # scope "/api", StandupWeb do
  #   pipe_through :api
  # end
end

lib/standup/organizations/domain.ex
defmodule Standup.Organizations.Domain do
  use Ecto.Schema
  import Ecto.Changeset
  alias Standup.Organizations.{Domain, Organization}


  schema "domains" do
    field :name, :string
    belongs_to :organization, Organization

    timestamps()
  end

  @doc false
  def changeset(%Domain{} = domain, attrs) do
    domain
    |> cast(attrs, [:name, :organization_id])
    |> validate_required([:name])
    |> unique_constraint(:name)
  end
end

lib/standup/organizations/organization.ex
defmodule Standup.Organizations.Organization do
  use Ecto.Schema
  import Ecto.Changeset
  alias Standup.Organizations.{Organization, UserOrganization, Team, Domain}
  alias Standup.Accounts.User
  alias Standup.StatusTrack.WorkStatus
  alias Standup.StatusTrack.WorkStatusType
  alias Standup.Spreadsheets.Spreadsheet


  schema "organizations" do
    field :description, :string
    field :name, :string
    many_to_many :users, User, join_through: UserOrganization  
    has_many :teams, Team
    has_many :work_statuses, WorkStatus
    has_many :work_status_types, WorkStatusType
    has_many :domains, Domain
    has_one :spreadsheet, Spreadsheet

    timestamps()
  end

  @doc false
  def changeset(%Organization{} = organization, attrs) do
    organization
    |> cast(attrs, [:name, :description])
    |> validate_required([:name])
  end
end

lib/standup/organizations/organizations.ex
defmodule Standup.Organizations do
  @moduledoc """
  The Organizations context.
  """

  require IEx

  import Ecto.Query, warn: false
  alias Standup.Repo
  alias Standup.Accounts.User

  alias Standup.Organizations.Domain
  alias Standup.Organizations.{Organization, UserOrganization, UserTeam, Team}

  @doc """
  Returns the list of organizations.

  ## Examples

      iex> list_organizations()
      [%Organization{}, ...]

  """
  def list_organizations do
    Repo.all(Organization)
  end

  def list_organizations(user) do
    query = from o in Organization,
    join:  u in assoc(o, :users), on: u.id == ^user.id
    Repo.all(query)
  end

  @doc """
  Gets a single organization.

  Raises `Ecto.NoResultsError` if the Organization does not exist.

  ## Examples

      iex> get_organization!(123)
      %Organization{}

      iex> get_organization!(456)
      ** (Ecto.NoResultsError)

  """
  def get_organization!(id), do: Repo.get!(Organization, id) |> Repo.preload([[users: :photo], :teams, :domains, :work_status_types, :spreadsheet])

  def get_organization_with_domains!(id), do: Repo.get!(Organization, id) |> Repo.preload([:domains])
  
  def get_organization_from_domain!(domain_name) do
    domain = Repo.get_by(Domain, name: domain_name) |> Repo.preload([:organization])
    if domain, do: domain.organization, else: nil
  end

  @doc """
  Creates a organization.

  ## Examples

      iex> create_organization(%{field: value})
      {:ok, %Organization{}}

      iex> create_organization(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_organization(conn, attrs \\ %{}) do
    current_user = conn.assigns.current_user
    result = %Organization{}
    |> Organization.changeset(attrs)
    |> Ecto.Changeset.put_assoc(:users, [current_user])
    |> Repo.insert()

    case result do
      {:ok , organization} -> 
        attrs = %{is_moderator: true}
        UserOrganization
        |> Repo.get_by(organization_id: organization.id)
        |> UserOrganization.changeset(attrs)
        |> Repo.update() 
    end
    result
  end

  @doc """
  Updates a organization.

  ## Examples

      iex> update_organization(organization, %{field: new_value})
      {:ok, %Organization{}}

      iex> update_organization(organization, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_organization(%Organization{} = organization, attrs) do
    organization
    |> Organization.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Organization.

  ## Examples

      iex> delete_organization(organization)
      {:ok, %Organization{}}

      iex> delete_organization(organization)
      {:error, %Ecto.Changeset{}}

  """
  def delete_organization(%Organization{} = organization) do
    Repo.delete(organization)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking organization changes.

  ## Examples

      iex> change_organization(organization)
      %Ecto.Changeset{source: %Organization{}}

  """
  def change_organization(%Organization{} = organization) do
    Organization.changeset(organization, %{})
  end

  @doc """
  Returns the list of teams.

  ## Examples

      iex> list_teams()
      [%Team{}, ...]

  """
  def list_teams do
    Repo.all(Team)
  end

  @doc """
  Gets a single team.

  Raises `Ecto.NoResultsError` if the Team does not exist.

  ## Examples

      iex> get_team!(123)
      %Team{}

      iex> get_team!(456)
      ** (Ecto.NoResultsError)

  """
  def get_team!(id), do: Repo.get!(Team, id) |> Repo.preload([:organization, :users])

  @doc """
  Creates a team.

  ## Examples

      iex> create_team(%{field: value})
      {:ok, %Team{}}

      iex> create_team(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_team(conn, attrs \\ %{}) do
    current_user = conn.assigns.current_user
    org = Organization |> Repo.get(attrs["organization_id"])
    result = %Team{}
    |> Team.changeset(attrs)
    |> Ecto.Changeset.put_assoc(:organization, org)
    |> Ecto.Changeset.put_assoc(:users, [current_user])
    |> Repo.insert()

    case result do
      {:ok , team} -> 
         set_as_moderator(team, current_user)
    end
    result
  end
  
  @doc """
  Updates a team.

  ## Examples

      iex> update_team(team, %{field: new_value})
      {:ok, %Team{}}

      iex> update_team(team, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_team(%Team{} = team, attrs) do
    team
    |> Team.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Team.

  ## Examples

      iex> delete_team(team)
      {:ok, %Team{}}

      iex> delete_team(team)
      {:error, %Ecto.Changeset{}}

  """
  def delete_team(%Team{} = team) do
    Repo.delete(team)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking team changes.

  ## Examples

      iex> change_team(team)
      %Ecto.Changeset{source: %Team{}}

  """
  def change_team(%Team{} = team) do
    Team.changeset(team, %{})
  end

  def add_users_to_team(team, user) do
    attrs = %{"team_id" => team.id, "user_id" => user.id}
    %UserTeam{}
    |> UserTeam.changeset(attrs)
    |> Repo.insert() 
  end

  def remove_users_from_team(team, user) do
    if get_user_team(team,user) do
        UserTeam
        |> Repo.get_by(team_id: team.id, user_id: user.id)
        |> Repo.delete() 
    else
      {:error, "user doesn't exist"}  
    end
  end

  def get_user_team(team,user) do
    UserTeam
    |> Repo.get_by(team_id: team.id, user_id: user.id)
  end

  def is_team_moderator?(team,user) do
    ut = get_user_team(team,user)
    if ut, do: ut.is_moderator, else: nil
  end

  def set_as_moderator(team,user) do
    attrs = %{is_moderator: true}
    get_user_team(team,user)
    |> UserTeam.changeset(attrs)
    |> Repo.update() 
  end

  def set_as_member(team,user) do
    attrs = %{is_moderator: false}
    get_user_team(team,user)
    |> UserTeam.changeset(attrs)
    |> Repo.update()
  end

  def is_current_user_moderator?(conn) do
    organization = hd(conn.assigns.current_user.organizations)
    is_org_moderator?(conn.assigns.current_user.id, organization.id)
  end

  def is_org_moderator?(user_id, org_id) do
    uo = UserOrganization
    |> Repo.get_by(organization_id: org_id, user_id: user_id)
    uo.is_moderator
  end

  def get_org_members(org_id) do
    query = from uo in UserOrganization,
    join: u in User,
    where: uo.user_id == u.id,
    where: uo.is_moderator == false and uo.organization_id == ^org_id, 
    select: u
    
    Repo.all(query)
  end

  def get_org_moderators(org_id) do
    query = from uo in UserOrganization,
    join: u in User,
    where: uo.user_id == u.id,
    where: uo.is_moderator == true and uo.organization_id == ^org_id, 
    select: u
    
    Repo.all(query)
  end

  def get_team_members(team_id) do
    query = from ut in UserTeam,
    join: u in User,
    where: ut.user_id == u.id,
    where: ut.is_moderator == false and ut.team_id == ^team_id,
    select: u
    
    users = Repo.all(query)
    users |> Repo.preload(:photo)
  end

  def get_team_moderators(team_id) do
    query = from ut in UserTeam,
    join: u in User,
    where: ut.user_id == u.id,
    where: ut.is_moderator == true and ut.team_id == ^team_id,
    select: u
    
    users = Repo.all(query)
    users |> Repo.preload(:photo)
  end

  def get_org_users(org_id) do
    query = from uo in UserOrganization,
    join: u in User,
    where: uo.user_id == u.id and uo.organization_id == ^org_id, 
    select: u
    
    Repo.all(query)
  end

  def get_team_users(team_id) do
    query = from ut in UserTeam,
    join: u in User,
    where: ut.user_id == u.id,
    where: ut.team_id == ^team_id,
    select: u
    
    users = Repo.all(query)
    users |> Repo.preload(:photo)
  end
  
  def get_org_users_for_team(team_id)  do
    team = Repo.get!(Team, team_id) |> Repo.preload([:organization, :users])
    org_id = team.organization.id
    team_users = Enum.map(team.users, fn(user) -> user.id end)

    query = from uo in UserOrganization,
    join: u in User,
    where: uo.user_id == u.id and uo.organization_id == ^org_id, 
    where: uo.user_id not in ^team_users,
    select: u
    
    Repo.all(query)
    |> Repo.preload(:photo)
  end

  def get_teams_by_user_and_org(user_id, org_id) do
    query = from ut in UserTeam,
    join: t in Team,
    where: ut.team_id == t.id and ut.user_id == ^user_id and t.organization_id == ^org_id, 
    select: t

    Repo.all(query)
  end

  @doc """
  Returns the list of domains.

  ## Examples

      iex> list_domains()
      [%Domain{}, ...]

  """
  def list_domains(org_id) do
    domains = from d in Domain,
    where: d.organization_id == ^org_id
    
    Repo.all(domains)
  end

  @doc """
  Gets a single domain.

  Raises `Ecto.NoResultsError` if the Domain does not exist.

  ## Examples

      iex> get_domain!(123)
      %Domain{}

      iex> get_domain!(456)
      ** (Ecto.NoResultsError)

  """
  def get_domain!(id), do: Repo.get!(Domain, id)

  @doc """
  Creates a domain.

  ## Examples

      iex> create_domain(%{field: value})
      {:ok, %Domain{}}

      iex> create_domain(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_domain(attrs \\ %{}, org) do
    %Domain{}
    |> Domain.changeset(attrs)
    |> Ecto.Changeset.put_assoc(:organization, org)
    |> Repo.insert()
  end

  @doc """
  Updates a domain.

  ## Examples

      iex> update_domain(domain, %{field: new_value})
      {:ok, %Domain{}}

      iex> update_domain(domain, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_domain(%Domain{} = domain, attrs) do
    domain
    |> Domain.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Domain.

  ## Examples

      iex> delete_domain(domain)
      {:ok, %Domain{}}

      iex> delete_domain(domain)
      {:error, %Ecto.Changeset{}}

  """
  def delete_domain(%Domain{} = domain) do
    Repo.delete(domain)
  end

  @doc """

lib/standup_web/controllers/organization_controller.ex
defmodule StandupWeb.OrganizationController do
  use StandupWeb, :controller

 # plug :authorize
  plug Standup.Plugs.OrganizationAuthorizer

  alias Standup.Organizations
  alias Standup.Organizations.Organization

 # @actions [:edit, :delete]


  def index(conn, _params) do
    current_user = conn.assigns.current_user
    organizations = Organizations.list_organizations(current_user)
    if Enum.count(organizations) > 0 do
      conn
      |> redirect(to: organization_path(conn, :show, hd(organizations)))
    else
      render(conn, "index.html", organizations: organizations)
    end
  end

  def new(conn, _params) do
    changeset = Organizations.change_organization(%Organization{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"organization" => organization_params}) do
    case Organizations.create_organization(conn, organization_params) do
      {:ok, organization} ->
        conn
        |> put_flash(:info, "Organization created successfully.")
        |> redirect(to: organization_path(conn, :show, organization))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    organization = Organizations.get_organization!(id)
    members = Organizations.get_org_members(id)
    moderators = Organizations.get_org_moderators(id)
    teams = organization.teams
    render(conn, "show.html", organization: organization, members: members, moderators: moderators, teams: teams)
  end

  def edit(conn, %{"id" => id}) do
    organization = Organizations.get_organization!(id)
    changeset = Organizations.change_organization(organization)
    render(conn, "edit.html", organization: organization, changeset: changeset)
  end

  def update(conn, %{"id" => id, "organization" => organization_params}) do
    organization = Organizations.get_organization!(id)

    case Organizations.update_organization(organization, organization_params) do
      {:ok, organization} ->
        conn
        |> put_flash(:info, "Organization updated successfully.")
        |> redirect(to: organization_path(conn, :show, organization))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", organization: organization, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    organization = Organizations.get_organization!(id)
    {:ok, _organization} = Organizations.delete_organization(organization)

    conn
    |> put_flash(:info, "Organization deleted successfully.")
    |> redirect(to: organization_path(conn, :index))
  end

  # def authorize(%Plug.Conn{:private => %{:phoenix_action => action}} = conn, _default) when action in @actions do
	# 	organization = hd(conn.assigns.current_user.organizations)
	# 	if Organizations.is_org_moderator?(conn.assigns.current_user.id, organization.id) do
	# 		assign(conn, :authorized, true)
	# 	else
	# 		assign(conn, :authorized, false)
	# 		Standup.Plugs.Authorizer.unauthorized_user(conn)
	# 	end
	# end
end

lib/standup_web/views/organization_view.ex
defmodule StandupWeb.OrganizationView do
  use StandupWeb, :view
end

lib/standup_web/templates/organization/edit.html.eex
<h2>Edit Organization</h2>

<%= render "form.html", Map.put(assigns, :action, organization_path(@conn, :update, @organization)) %>

lib/standup_web/templates/organization/new.html.eex
<h4>New Organization</h4>

<%= render "form.html", Map.put(assigns, :action, organization_path(@conn, :create)) %>

lib/standup_web/templates/organization/show.html.eex
<div class="card-panel grey lighten-5"> 
<div class="valign-wrapper right">
  <%= link "Edit", to: organization_path(@conn, :edit, @organization), class: "btn ", style: "margin-right: 5px;" %>
  <%= link "Delete", to: organization_path(@conn, :delete, @organization), method: :delete, data: [confirm: "Are you sure?"], class: "btn" %>
</div>

<h4>Organization:  <%= @organization.name %></h4>
<%= @organization.description %>
</div>

<div class="row m-0">
<div class="col s12 m6">
<div class="card ">
<div class="card-content cyan darken-1 white-text" style="position: relative">
  <span class="card-title m-b-0">Self signup email address domains</span>
</div>
<div class="card-content grey lighten-5">
<table class="bordered highlight">
  <thead>
    <tr>
      <th>Name</th>

      <th class="right">
      <span class='<%= unless is_current_user_moderator?(@conn), do: "hide" %>'><%= link "New Domain", to: organization_domain_path(@conn, :new, @organization), class: "btn right light" %></span>

      </th>
    </tr>
  </thead>
  <tbody>
  <%= if Enum.count(@organization.domains) == 0 do %>
  <tr>
      <td colspan="2">
        <h6 class="center">No domains created yet!</h6>
      </td>
  </tr>
  <% end %>
<%= for domain <- @organization.domains do %>
    <tr>
      <td><%= domain.name %></td>
      <td>
        <div class="right">
          <a class='dropdown-button btn' href='#' data-activates='dropdown_domain_<%= domain.id %>'>Action</a>
          <ul id='dropdown_domain_<%= domain.id %>' class='dropdown-content'>
            <li><%= link "Show", to: organization_domain_path(@conn, :show, @organization, domain), class: "" %></li>
            <li><%= link "Edit", to: organization_domain_path(@conn, :edit, @organization, domain), class: "" %></li>
            <li><%= link "Delete", to: organization_domain_path(@conn, :delete, @organization, domain), method: :delete, data: [confirm: "Are you sure?"], class: "" %></li>
          </ul>
        </div>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
</div>
</div>
</div>
<div class="col s12 m6"> 
<div class="card ">
<div class="card-content cyan darken-1 white-text" style="position: relative">
  <span class="card-title m-b-0">Teams</span>
</div>
<div class="card-content grey lighten-5">
<table class="bordered highlight">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>

      <th class="right">
        <span><%= link "Create", to: team_path(@conn, :new, organization_id: @organization.id ), class: "btn right light" %></span>
      </th>
    </tr>
  </thead>
  <tbody>

<%= if Enum.count(@teams) == 0 do %>
 <tr>
    <td colspan="2">
      <h6 class="center">No teams created yet!</h6>
    </td>
 </tr>
<% end %>

<%= for team <- @teams do %>
    <tr>
      <td><%= team.name %></td>
      <td><%= team.description %></td>
      <td class="right">
        <a class='dropdown-button btn' href='#' data-activates='dropdown_team_<%= team.id %>'>Action</a>
        <ul id='dropdown_team_<%= team.id %>' class='dropdown-content'>
          <li><a href="<%= team_path(@conn, :show, team) %>" class="">Show</a></li>
          <li><a href="<%= team_path(@conn, :edit, team) %>" class="">Edit</a></li>
          <li><%= link to: team_path(@conn, :delete, team), method: :delete, data: [confirm: "Are you sure?"], class: "" do %>
                Delete
              <% end %>
          </li>
        </ul>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
</div>
</div>
</div>
</div>
<div class="row m-0">
<div class="col s12 m6">
<div class="card ">
<div class="card-content cyan darken-1 white-text" style="position: relative">
  <span class="card-title m-b-0">Add Work Status Type</span>
</div>
<div class="card-content grey lighten-5">
<table class="bordered highlight">
  <thead>
    <tr>
      <th>Name</th>

      <th class="right">
      <span><%= link "New Work status type", to: organization_work_status_type_path(@conn, :new, @organization), class: "btn right light" %></span>

      </th>
    </tr>
  </thead>
  <tbody>
  <%= if Enum.count(@organization.work_status_types) == 0 do %>
  <tr>
      <td colspan="2">
        <h6 class="center">No work status type created yet!</h6>
      </td>
  </tr>
  <% end %>
<%= for work_status_type <- @organization.work_status_types do %>
    <tr>
      <td><%= work_status_type.name %></td>
      <td>
        <div class="right">
          <a class='dropdown-button btn' href='#' data-activates='dropdown_work_status_type_<%= work_status_type.id %>'>Action</a>
          <ul id='dropdown_work_status_type_<%= work_status_type.id %>' class='dropdown-content'>
            <li><%= link "Show", to: organization_work_status_type_path(@conn, :show, @organization, work_status_type), class: "" %></li>
            <li><%= link "Edit", to: organization_work_status_type_path(@conn, :edit, @organization, work_status_type), class: "" %></li>
            <li><%= link "Delete", to: organization_work_status_type_path(@conn, :delete, @organization, work_status_type), method: :delete, data: [confirm: "Are you sure?"], class: "" %></li>
          </ul>
        </div>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
</div>
</div>
</div>

<div class="col s12 m6">
<div class="card ">
<div class="card-content cyan darken-1 white-text" style="position: relative">
  <span class="card-title m-b-0">Spreadsheet</span>
</div>
<div class="card-content grey lighten-5">
<table class="bordered highlight">
  <thead>
    <tr>
      <th>Spreadsheet status</th>

      <th class="right">
      <%= unless @organization.spreadsheet do %>
        <span><%= link "New Spreadsheet", to: organization_spreadsheet_path(@conn, :new, @organization), class: "btn right light" %></span>
      <% end %>
      </th>
    </tr>
  </thead>
  <tbody>
  <%= unless @organization.spreadsheet do %>
  <tr>
      <td colspan="2">
        <h6 class="center">No Spreadsheet added yet!</h6>
      </td>
  </tr>
  <% else %>
    <tr>
      <td><%= @organization.spreadsheet.status %></td>
      <td>
        <div class="right">
          <a class='dropdown-button btn' href='#' data-activates='dropdown_spreadsheet_<%= @organization.spreadsheet.id %>'>Action</a>
          <ul id='dropdown_spreadsheet_<%= @organization.spreadsheet.id %>' class='dropdown-content'>
            <li><%= link "Show", to: organization_spreadsheet_path(@conn, :show, @organization, @organization.spreadsheet), class: "" %></li>
            <li><%= link "Edit", to: organization_spreadsheet_path(@conn, :edit, @organization, @organization.spreadsheet), class: "" %></li>
            <li><%= link "Delete", to: organization_spreadsheet_path(@conn, :delete, @organization, @organization.spreadsheet), method: :delete, data: [confirm: "Are you sure?"], class: "" %></li>
          </ul>
        </div>
      </td>
    </tr>
    <tr>
      <td colspan=2>
         <strong><p>Please share your Google speadsheet document with the below email for the App to push workstatus updates.</p></strong>
        <div class="chip " style="white-space:nowrap;">
          standup@standup-129.iam.gserviceaccount.com
        </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>
</div>
</div>

</div>

<div class="row m-0">
<div class="col s12">
<div class="card ">
<div class="card-content cyan darken-1 white-text" style="position: relative">
  <span class="card-title m-b-0">Users</span>
</div>
<div class="card-content grey lighten-5">
<table class=" bordered highlight ">
  <thead>
    <tr>
      <th>Name</th>
      <%# <th>Username</th> %>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @organization.users do %>
    <tr>
      <td>
        <div class="m-b-0">
          <div class="left avatar">
            <%= unless is_nil(user.photo) do %>
              <%= cl_image_tag(user.photo.public_id, class: "circle responsive-img", transforms: %{width: 50, height: 50, sign_url: true, quality: 80, crop: :fill, gravity: :face}) %>
            <% end %> 
          </div>
          <div class="left" style="margin: 15px 10px; ">
            <b class="cyan-text text-darken-4"> <%= user.firstname %>  <%= user.lastname %></b>
          <span class='new badge <%= if Enum.any?(@moderators, fn(u) -> u.id == user.id end), do: "pink", else: "cyan" %>' data-badge-caption="">
            <%= if Enum.any?(@moderators, fn(u) -> u.id == user.id end), do: "Moderator", else: "Member" %>
          </span>
          </div>
        </div>
      </td>
      <td class="right">
        <a class='dropdown-button btn ' style="margin-top: 15px; " href='#' data-activates='dropdown_user_<%= user.id %>'>Action</a>
          <ul id='dropdown_user_<%= user.id %>' class='dropdown-content'>
            <li><%= link "Show", to: user_path(@conn, :show, user), class: "" %></li>
            <li><%= link "Edit", to: user_path(@conn, :edit, user), class: "" %></li>
            <li><%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "" %></li>
          </ul>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
</div>
</div>
</div>
</div>
<br>
<span><%#= link "Back", to: organization_path(@conn, :index), class: "btn" %></span>