lib/standup_web/router.ex
defmodule StandupWeb.Router do
  use StandupWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Pjax.Plugs.Pjax)
  end

  # pipeline :browser_auth do
  #   plug Guardian.Plug.VerifySession
  #   plug Guardian.Plug.EnsureAuthenticated, handler: Standup.AuthErrorHandler
  #   plug Guardian.Plug.LoadResource, allow_blank: true
  #   plug Standup.CurrentUser
  # end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end
  pipeline :browser_session do
    plug(Standup.Guardian.AuthPipeline.Browser)
    plug(Standup.Auth.CurrentUser)
  end

  pipeline :login_required do
    plug(Standup.Guardian.AuthPipeline.Authenticate)
  end

  # pipeline :authorize_admin do
  #   plug Standup.Guardian.AuthPipeline.Authenticate
  #   plug Standup.Auth.Authorize, :admin
  # end

  pipeline :api do
    plug(:accepts, ["json"])
    plug(Standup.Guardian.AuthPipeline.JSON)
  end

  scope "/auth", StandupWeb do
    pipe_through([:browser, :browser_session])

    get("/:provider", AuthController, :new)
    get("/:provider/callback", AuthController, :callback)
    post("/identity/callback", AuthController, :identity_callback)
    delete("/delete", AuthController, :delete)
  end

  scope "/", StandupWeb do
    pipe_through([:browser, :browser_session])

    resources("/users", UserController, only: [:new, :create])
  end

  scope "/", StandupWeb do
    # Use the default browser stack
    pipe_through([:browser, :browser_session, :login_required])

    get("/", PageController, :index)
    resources("/users", UserController, except: [:new, :create])
    resources("/roles", RoleController)

    resources "/organizations", OrganizationController do
      resources("/domains", DomainController)
      resources("/work_status_types", WorkStatusTypeController)
      resources("/spreadsheets", SpreadsheetController)
      resources("/to_dos", ToDoController)
    end

    resources "/to_dos", ToDoController, only: [], as: :to_do do
      resources("/to_do_users", ToDoUserController, as: :users)
    end

    resources "/teams", TeamController do
      get("/add_users", TeamController, :add_users, as: :add_users)
      get("/remove_users", TeamController, :remove_users, as: :remove_users)
      get("/set_as_moderator", TeamController, :set_as_moderator, as: :set_as_moderator)
      get("/set_as_member", TeamController, :set_as_member, as: :set_as_member)
    end

    post("/photos/upload", PhotoController, :upload)

    resources "/work_statuses", WorkStatusController do
      resources("/key_result_areas", KeyResultAreaController)
      resources("/comments", CommentController)
    end

    get("/team_work_statuses", WorkStatusController, :team_work_statuses, as: :team_work_statuses)
    resources("/tasks", TaskController)

    get(
      "/export_to_do_to_tasks",
      TaskController,
      :export_to_do_to_tasks,
      as: :export_to_do_to_tasks
    )

    get("/team_to_dos", ToDoController, :team_to_dos, as: :team_to_dos)
  end

  # Other scopes may use custom stacks.
  # scope "/api", StandupWeb do
  #   pipe_through :api
  # end
end

lib/standup/status_track/key_result_area.ex
defmodule Standup.StatusTrack.KeyResultArea do
  use Ecto.Schema
  import Ecto.Changeset
  alias Standup.StatusTrack.KeyResultArea
  alias Standup.StatusTrack.WorkStatus


  schema "key_result_areas" do
    field :accountability, :string
    field :effective_communication, :boolean, default: false
    field :impediments, :string
    field :ownership, :string
    field :productivity, :float
    field :skill, :string
    belongs_to :work_status, WorkStatus

    timestamps()
  end

  @doc false
  def changeset(%KeyResultArea{} = key_result_area, attrs) do
    key_result_area
    |> cast(attrs, [:accountability, :ownership, :productivity, :skill, :effective_communication, :impediments, :work_status_id])
    |> validate_required([ :productivity,  :effective_communication])
  end
end

lib/standup_web/controllers/key_result_area_controller.ex
defmodule StandupWeb.KeyResultAreaController do
  use StandupWeb, :controller
  plug Standup.Plugs.KeyResultAreaAuthorizer

  require IEx
  alias Standup.StatusTrack
  alias Standup.StatusTrack.KeyResultArea

  def index(conn, %{"work_status_id" => work_status_id}) do
    work_status = StatusTrack.get_work_status!(work_status_id)
    key_result_areas = StatusTrack.list_key_result_areas()
    render(conn, "index.html", key_result_areas: key_result_areas, work_status: work_status)
  end

  def new(conn, %{"work_status_id" => work_status_id}) do
    work_status = StatusTrack.get_work_status!(work_status_id)
    changeset = StatusTrack.change_key_result_area(%KeyResultArea{work_status_id: work_status_id})
    case work_status.key_result_area do
      %KeyResultArea{} = key_result_area -> 
          conn |> redirect(to: work_status_key_result_area_path(conn, :edit, work_status_id, key_result_area))
      _ ->
        render(conn, "new.html", changeset: changeset, work_status: work_status)
    end
  end

  def create(conn, %{"key_result_area" => key_result_area_params, "work_status_id" => work_status_id}) do
    case StatusTrack.create_key_result_area(key_result_area_params) do
      {:ok, key_result_area} ->
        conn
        |> put_flash(:info, "Key result area created successfully.")
        |> redirect(to: work_status_key_result_area_path(conn, :show, work_status_id, key_result_area))
      {:error, %Ecto.Changeset{} = changeset} ->
        work_status = StatusTrack.get_work_status!(work_status_id)
        render(conn, "new.html", changeset: changeset, work_status: work_status)
    end
  end

  def show(conn, %{"id" => id}) do
    key_result_area = StatusTrack.get_key_result_area!(id)
    render(conn, "show.html", key_result_area: key_result_area, work_status: key_result_area.work_status)
  end

  def edit(conn, %{"id" => id}) do
    key_result_area = StatusTrack.get_key_result_area!(id)
    changeset = StatusTrack.change_key_result_area(key_result_area)
    render(conn, "edit.html", key_result_area: key_result_area, changeset: changeset, work_status: key_result_area.work_status)
  end

  def update(conn, %{"id" => id, "key_result_area" => key_result_area_params}) do
    key_result_area = StatusTrack.get_key_result_area!(id)

    case StatusTrack.update_key_result_area(key_result_area, key_result_area_params) do
      {:ok, key_result_area} ->
        conn
        |> put_flash(:info, "Key result area updated successfully.")
        |> redirect(to: work_status_key_result_area_path(conn, :show, key_result_area.work_status, key_result_area, work_status: key_result_area.work_status))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", key_result_area: key_result_area, changeset: changeset, work_status: key_result_area.work_status)
    end
  end

  def delete(conn, %{"id" => id, "work_status_id" => work_status_id}) do
    key_result_area = StatusTrack.get_key_result_area!(id)
    {:ok, _key_result_area} = StatusTrack.delete_key_result_area(key_result_area)

    conn
    |> put_flash(:info, "Key result area deleted successfully.")
    |> redirect(to: work_status_key_result_area_path(conn, :index, work_status_id))
  end
end

lib/standup_web/views/key_result_area_view.ex
defmodule StandupWeb.KeyResultAreaView do
  use StandupWeb, :view
end

lib/standup_web/templates/key_result_area/edit.html.eex
<h4>Edit Key result area</h4>

<%= render "form.html", Map.put(assigns, :action, work_status_key_result_area_path(@conn, :update, @work_status, @key_result_area)) %>

lib/standup_web/templates/key_result_area/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="card red lighten-5" role="alert">
      <div class="card-content red-text">
        <p> Please check the errors below.</p>
      </div>
    </div>
  <% end %>

  <%= if Map.has_key?(@changeset.changes, :accountability) do %>
  <div class="row">
    <div class="input-field col s12">
      <%= label f, :accountability, class: "active" %>
      <%= textarea f, :accountability, class: "hide" %>
        <%= if @changeset.changes.accountability do %>
          <p class="html-newline"><%= @changeset.changes.accountability %></p>
        <% else %>
          <p class="html-newline"><%= @changeset.data.accountability %></p>
        <% end %>
      <%= error_tag f, :accountability %>
    </div>
  </div>
  <% end %>
  <%= hidden_input f, :work_status_id %>

  <div class="row">
    <div class="input-field col s12 m6">
      <%= label f, :ownership %>
      <%= textarea f, :ownership, class: "materialize-textarea" %>
      <%= error_tag f, :ownership %>
    </div>

    <div class="input-field col s12 m6">
      <%= label f, :skill %>
      <%= textarea f, :skill, class: "materialize-textarea" %>
      <%= error_tag f, :skill %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12 m6">
      <%= label f, :productivity, "Productivity (%)" %>
      <%= number_input f, :productivity, step: "any" %>
      <%= error_tag f, :productivity %>
    </div>

    <div class="input-field col s6 m3">
      <label>Effective Communication</label>
    </div>
    <div class="col s6 m3">
      <p>
        <%= radio_button f, :effective_communication, true, class: "with-gap" %>
        <label for="key_result_area_effective_communication_true">Yes</label>
      </p>
      <p>
        <%= radio_button f, :effective_communication, false, class: "with-gap" %>
        <label for="key_result_area_effective_communication_false">No</label>
      </p>
 
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= label f, :impediments %>
      <%= textarea f, :impediments, class: "materialize-textarea" %>
      <%= error_tag f, :impediments %>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <%= submit "Submit", class: "btn waves-effect waves-light" %>
      <a href="javascript:history.back()" class="waves-effect waves-light btn">Back</a>
    </div>
  </div>
<% end %>

lib/standup_web/templates/key_result_area/index.html.eex
<h4>Key result areas</h4>

<table class="table">
  <thead>
    <tr>
      <th>Accountability</th>
      <th>Ownership</th>
      <th>Productivity</th>
      <th>Skill</th>
      <th>Effective communication</th>
      <th>Impediments</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for key_result_area <- @key_result_areas do %>
    <tr>
      <td><%= key_result_area.accountability %></td>
      <td><%= key_result_area.ownership %></td>
      <td><%= key_result_area.productivity %></td>
      <td><%= key_result_area.skill %></td>
      <td><%= key_result_area.effective_communication %></td>
      <td><%= key_result_area.impediments %></td>

      <td class="text-right">
        <span><%= link "Show", to: work_status_key_result_area_path(@conn, :show, @work_status, key_result_area), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: work_status_key_result_area_path(@conn, :edit, @work_status, key_result_area), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: work_status_key_result_area_path(@conn, :delete, @work_status, key_result_area), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Key result area", to: work_status_key_result_area_path(@conn, :new, @work_status) %></span>

lib/standup_web/templates/key_result_area/new.html.eex
<h4>New Key Result Area</h4>
<br>
<%= render "form.html", Map.put(assigns, :action, work_status_key_result_area_path(@conn, :create, @work_status)) %>

lib/standup_web/templates/key_result_area/show.html.eex
<h4>Show Key result area</h4>

<ul>

<%= if @key_result_area.accountability do %>
  <li>
    <strong>Accountability:</strong>
    <p class="html-newline"><%= @key_result_area.accountability %></p>
  </li>
<% end %>
  
<%= if @key_result_area.ownership do %>
  <li>
    <strong>Ownership:</strong>
    <p class="html-newline"><%= @key_result_area.ownership %></p>
  </li>
<% end %>

  <li>
    <strong>Productivity:</strong>
    <%= @key_result_area.productivity %> %
  </li>
  
<%= if @key_result_area.skill do %>
  <li>
    <strong>Skill:</strong>
    <%= @key_result_area.skill %>
  </li>
<% end %>

  <li>
    <strong>Effective communication:</strong>
    <%= @key_result_area.effective_communication %>
  </li>
  
<%= if @key_result_area.impediments do %>
  <li>
    <strong>Impediments:</strong>
    <%= @key_result_area.impediments %>
  </li>
<% end %>

</ul>

<span><%= link "Edit", to: work_status_key_result_area_path(@conn, :edit, @key_result_area.work_status, @key_result_area), class: "btn" %></span>
<span><a href="<%= work_status_path(@conn, :show, @key_result_area.work_status) %>" class="waves-effect waves-light btn">Back</a></span>